### PR TITLE
STAC 1.0 compatibility, release 0.3.0

### PR DESCRIPTION
**Pull request by scottyhq**
Addresses https://github.com/intake/intake-stac/issues/57

Currently hitting `ValueError: Can't clean for JSON:` for 
```python
    catalog = catalog['hurricane-harvey']['hurricane-harvey-0831']
    for id, entry in catalog.items():
        display(entry)
``` 
https://github.com/intake/intake-stac/issues/31 

cc @jhamman - i'm wondering if we can directly render one of the notebooks under examples/ in the docs instead of a separate tutorial.rst

### CODE REVIEW

**Comment by scottyhq** [comment]
just bypassing #31 for now and instead modifying the tutorial.rst code blocks to clarify usage. @jhamman - i'd like to get a 0.3 version out, any other must-haves before doing that?

**Comment by jhamman** [comment]
@scottyhq - this looks good. Can you rebase / merge after #63 and then I'll take a final pass tomorrow. Happy to make a release once this gets merged!

**Comment by scottyhq** [comment]
Some failing tests for intake upstream:

```python
item = StacItem(stac_item_obj)
list_of_bands = ['B1', 'B8']
B1_da = item.B1.to_dask()

url = 'https://landsat-pds.s3.amazonaws.com/c1/L8/152/038/LC08_L1TP_152038_20200611_20200611_01_RT/LC08_L1TP_152038_20200611_20200611_01_RT_B1.TIF'
169
mode = 'rb', storage_options = {}, of = <List of 1 OpenFile instances>
E           ValueError: open_local can only be used on a filesystem which has attribute local_file=True
```

Full log:
https://github.com/intake/intake-stac/pull/61/checks?check_run_id=1194455402 


@martindurant @jhamman -not sure why the URLs are not passed to open_local?..

Could also fix in a subsequent PR. I think this is ready to merge and release.

**Comment by martindurant** [comment]
This is probably due to the release of intake-xarray; please forward or reference this issue there. I think it probably has to do with the distinction between file-based and URL-based open functions.

**Comment by scottyhq** [comment]
@jhamman - since tests pass with intake-xarray 0.3.1, should we just pin to that version and release?

**Comment by jhamman** [comment]
> @jhamman - since tests pass with intake-xarray 0.3.1, should we just pin to that version and release?

Perhaps it would be best to if we just xfailed this test for intake-xarray > 0.3.1? Hopefully upstream is fixed before we release again.

**Comment by scottyhq** [comment]
finally! read-the-docs woes sorted. python3.9 environment failing to solve with conda, but i'm going to squash and merge this and release and hope that new dependency versions on conda-forge will be sorted soon.

**Pull request merged**
