### PR TITLE
add "application/xml" to dictionary of drivers

### PR DESCRIPTION
**Pull request by fnattino**
Fix for #97

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Thanks, can you add a small test for this?

And if you merge `main` and repush then the CI failures should be fixed.

**Comment by fnattino** [comment]
Hi @TomAugspurger , sure! I have added a test based on the single-file STAC that was already in the repo, checking whether the media types for all assets are listed in the drivers dictionary. I have also thought it was a good idea to check whether all common media types listed in PySTAC are also listed among the drivers, and realised that `image/tiff` is actually missing. Should I add it to the dictionary as well (I guess with `rasterio` as driver)?

**Comment by TomAugspurger** [comment]
Thanks, that would be great. Either here or as a followup would be fine.

**Comment by TomAugspurger** [comment]
Thanks @fnattino!

**Pull request merged**
